/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface AALLRatingApiKeys {
  ApiKey: string | null;
  ClientID: string | null;
  DateExpired: Date | null;
  DateIssued: Date | null;
  ID: Generated<number>;
}

export interface AutoDriver {
  CreatedDate: Generated<Date | null>;
  DriverDOB: Date | null;
  DriverFirstName: string | null;
  DriverLastName: string | null;
  DriverMiddleName: string | null;
  DriverNumber: number | null;
  DriverUID: Generated<string>;
  Excluded: Generated<boolean>;
  Gender: string | null;
  InsuredUID: string;
  LicenseNumber: string | null;
  LicenseState: string | null;
  LicenseStatus: string | null;
  LicenseType: string | null;
  MaritalStatus: string | null;
  Occupation: string | null;
  Relationship: string | null;
  SR22: Generated<boolean>;
}

export interface AutoInsured {
  AALLCarrier: string | null;
  AALLCustomerID: number | null;
  AALLExpiration: Date | null;
  AALLPolicyNumber: string | null;
  AALLPremium: number | null;
  AbsoluteUncheckReason: string | null;
  Address1: string | null;
  AddressValidated: Generated<boolean>;
  AgencyInternalTransfer: Generated<boolean>;
  BILimit: string | null;
  CarrierOffered: string | null;
  City: string | null;
  County: string | null;
  CreatedByCSR: string | null;
  CreatedByName: string | null;
  CreatedDate: Generated<Date | null>;
  CurrentMonthlyPremium: number | null;
  DOB: Date | null;
  DoRunCredit: Generated<boolean>;
  DownPmtOffered: number | null;
  DupCheckRan: Generated<boolean>;
  EmailAddress: string | null;
  FeeOffered: number | null;
  GaragingAddress1: string | null;
  GaragingCity: string | null;
  GaragingState: string | null;
  GaragingUnitNumber: string | null;
  GaragingZipCode: string | null;
  HasEbilling: Generated<boolean>;
  InsuredFirstName: string | null;
  InsuredLastName: string | null;
  InsuredMiddleName: string | null;
  InsuredUID: Generated<string>;
  InsuredWith: string | null;
  IsAPIQuote: Generated<boolean>;
  IsCancelOver45: Generated<boolean>;
  IsCurrentlyInsured: string | null;
  IsDup: Generated<boolean>;
  IsGaragingDifferentThanMailing: Generated<boolean>;
  IsHomeOwner: Generated<boolean>;
  IsNonOwners: Generated<boolean>;
  IsPhone: Generated<boolean>;
  IsRateTest: Generated<boolean | null>;
  IsWebQuote: Generated<boolean>;
  LastQuotedByCSR: string | null;
  LastSavedByCSR: string | null;
  LastSavedByName: string | null;
  LastSavedByOffice: string | null;
  LastSavedDate: Date | null;
  LeadingDigit: Generated<number | null>;
  LeadSource: string | null;
  MedPm: string | null;
  MonthlyOffered: number | null;
  MonthsAtAddress: number | null;
  NonOwnersQ1: Generated<boolean>;
  NonOwnersQ2: Generated<boolean>;
  NonOwnersQ3: Generated<boolean>;
  Office: string | null;
  OtherShoppingReason: string | null;
  PaymentPlan: string | null;
  PDLimit: string | null;
  PhoneNumber: string | null;
  PolicyEffectiveDate: Date | null;
  PolicyExpirationDate: Date | null;
  PrefillDriversDisplayed: Generated<boolean>;
  PrefillSent: Generated<boolean>;
  PrefillVehiclesDisplayed: Generated<boolean>;
  PreviousAddress1: string | null;
  PreviousCity: string | null;
  PreviousState: string | null;
  PreviousUnitNumber: string | null;
  PreviousZipCode: string | null;
  QualifiesForPrefill: Generated<boolean>;
  QuoteCustomerID: number | null;
  QuoteNumber: number | null;
  QuoteType: string | null;
  ReasonForLeaving: string | null;
  ReasonNotHappy: string | null;
  ReasonNotSold: string | null;
  ReasonNotSoldAddlNotes: string | null;
  ReasonNotSoldDetails: string | null;
  ReasonShopping: string | null;
  ResidenceType: string | null;
  SelectedLanguage: string | null;
  SoldByCSR: string | null;
  State: string | null;
  TRQuoteID: number | null;
  UIMBILimit: string | null;
  UMBILimit: string | null;
  UnitNumber: string | null;
  WasQuoteSoldAnswer: string | null;
  WasReasonNotSoldNoteAdded: Generated<boolean>;
  YearsAtAddress: number | null;
  ZipCode: string | null;
}

export interface AutoInsuredPriorPolicy {
  BILimit: string | null;
  CarrierName: string | null;
  InsuredUID: string;
  MonthsWithInsurer: number | null;
  NAICCode: string | null;
  PDLimit: string | null;
  PolicyEffectiveDate: Date | null;
  PolicyExpirationDate: Date | null;
  PolicyNumber: string | null;
  PriorRenewalPrice: number | null;
  RenewalPrice: number | null;
}

export interface AutoNote {
  CreatedBy: string | null;
  CreatedDate: Generated<Date | null>;
  DisplayOnMainPage: Generated<boolean | null>;
  InsuredUID: string;
  NoteText: string | null;
  NoteType: string | null;
  NoteUID: Generated<string>;
}

export interface AutoPrefillDriver {
  Action: string | null;
  CreatedDate: Generated<Date | null>;
  DOB: Date | null;
  FirstName: string | null;
  Gender: string | null;
  InsuredUID: string;
  LastName: string | null;
  PrefillDriverUID: Generated<string>;
}

export interface AutoPrefillVehicle {
  Action: string | null;
  BodyStyle: string | null;
  Confidence: number | null;
  CreatedDate: Generated<Date | null>;
  InsuredUID: string;
  Make: string | null;
  Model: string | null;
  PlateNumber: string | null;
  PrefillVehicleUID: Generated<string>;
  PurchaseDate: string | null;
  RegisteredOwner: string | null;
  Type: string | null;
  VIN: string | null;
  Year: string | null;
}

export interface AutoRateLineItem {
  AutoRateLineItemUID: Generated<string>;
  AutoRateRequestUID: string | null;
  BridgedDate: Date | null;
  Carrier: string | null;
  CreatedDate: Generated<Date | null>;
  MainRate: number | null;
  QuoteURL: string | null;
  StringResponse: string | null;
}

export interface AutoRateRequest {
  AutoRateRequestUID: Generated<string>;
  CoverageSummary: string | null;
  CreatedDate: Generated<Date | null>;
  DriverSummary: string | null;
  InsuredUID: string;
  QuotedBy: string | null;
  VehicleSummary: string | null;
  ViolationSummary: string | null;
}

export interface AutoVehicle {
  BodyType: string | null;
  CollDed: string | null;
  CompDed: string | null;
  CreatedDate: Generated<Date | null>;
  CustomEquipment: string | null;
  DailyMileage: number | null;
  ExistingDamage: string | null;
  FullGlass: Generated<string | null>;
  InsuredUID: string;
  IsIncludedInQuote: Generated<boolean>;
  IsManualOverride: Generated<boolean>;
  IsValidated: Generated<boolean>;
  LPP: string | null;
  Make: string | null;
  Mileage: number | null;
  Model: string | null;
  Modifications: string | null;
  NonOwned: Generated<boolean | null>;
  OwnershipType: string | null;
  PrimaryDriverNumber: string | null;
  PurchaseDate: Date | null;
  Rental: string | null;
  SalvagedRestored: string | null;
  Towing: string | null;
  Trim: string | null;
  UMPD: number | null;
  UsedFor: string | null;
  UsedForRideShare: Generated<boolean>;
  VehicleNumber: number | null;
  VehicleUID: Generated<string>;
  VIN: string | null;
  Year: number | null;
}

export interface AutoViolation {
  CreatedDate: Generated<Date | null>;
  DriverNumber: string | null;
  InsuredUID: string;
  ViolationDate: Date | null;
  ViolationDescription: string | null;
  ViolationUID: Generated<string>;
}

export interface AutoWebQuote {
  CustomerSelectedCarrier: string | null;
  DidCustomerCall: boolean | null;
  InsuredUID: string;
  IsCurrentOrPreviousCustomer: boolean | null;
  ResumeQuoteSection: string | null;
  ScheduledCallbackDateTime: Date | null;
  UninsuredReason: string | null;
  wasAgentQuoteAbandonedEmailSent: boolean | null;
  wasAgentQuoteFinishedEmailSent: boolean | null;
  wasAgentScheduledCallbackEmailSent: boolean | null;
  wasUserInitialEmailSent: boolean | null;
  wasUserQuoteFinishedEmailSent: boolean | null;
  WebLeadSource: string | null;
  WebLeadSourceDescription: string | null;
  WebProgress: string | null;
}

export interface AutoWebQuoteRates {
  CarrierCode: string | null;
  CarrierName: string | null;
  Deposit: number | null;
  Installment: number | null;
  InsuredUID: string | null;
  IsPreferred: boolean | null;
  IsRecommended: boolean | null;
  IsSelected: boolean | null;
  RateUID: string;
  StringResponse: string | null;
  Total: number | null;
}

export interface CarrierFieldMap {
  Carrier: string | null;
  FieldName: string | null;
  MappedValue: string | null;
  OriginalValue: string | null;
  UID: Generated<string>;
}

export interface CarrierNameOption {
  CarrierName: string | null;
  ID: Generated<number>;
}

export interface CarrierQuestion {
  CarrierCode: string;
  ExclusionOptions: string | null;
  IsQualifyingQuestion: Generated<boolean | null>;
  IsRatingQuestion: boolean | null;
  OptionList: string | null;
  QuestionText: string | null;
}

export interface CarrierQuoteRule {
  CarrierCode: string | null;
  CarrierQuoteExclusionUID: Generated<string>;
  DisplayMessage: string | null;
  DriverNumber: number | null;
  ExcludeQuote: Generated<boolean>;
  ExclusionField: string | null;
  ExclusionOperator: string | null;
  ExclusionTable: string | null;
  ExclusionValue: string | null;
  HasUnless: Generated<boolean>;
  UnlessField: string | null;
  UnlessOperator: string | null;
  UnlessTable: string | null;
  UnlessValue: string | null;
}

export interface CarrierRateInfo {
  CarrierCode: string;
  CarrierCodeForCRM: string | null;
  FullName: string | null;
  IsActiveAuto: Generated<boolean | null>;
  IsActiveForRateTest: Generated<boolean | null>;
  IsActiveHome: Generated<boolean | null>;
  IsActiveRenters: boolean | null;
  LogoPath: string | null;
  ProdEndpointAuto: string | null;
  ProdEndpointHome: string | null;
  ProdEndpointRenters: string | null;
  SkipTestEnvAuto: Generated<boolean | null>;
  TestEndpointAuto: string | null;
  TestEndpointHome: string | null;
  TestEndpointRenters: string | null;
}

export interface CarrierUser {
  EmailAddress: string | null;
  PasswordHash: string | null;
  UID: Generated<string | null>;
}

export interface CarrierViolationMap {
  CarrierCode: string | null;
  CarrierValue: string | null;
  UID: Generated<string>;
  ViolationDescription: string | null;
}

export interface ErrorLog {
  CreatedDate: Generated<Date | null>;
  CSR: string | null;
  ErrorLogUID: Generated<string>;
  InnerException: string | null;
  Message: string | null;
  ReferenceUID: string | null;
  StackTrace: string | null;
  UserName: string | null;
}

export interface HomeAdditionalInsured {
  CreatedDate: Generated<Date | null>;
  DOB: Date | null;
  FirstName: string | null;
  Gender: string | null;
  HomeAdditionalInsuredUID: Generated<string>;
  HomeInsuredUID: string;
  LastName: string | null;
  MaritalStatus: string | null;
  MiddleName: string | null;
  Occupation: string | null;
  Relationship: string | null;
}

export interface HomeCoverage {
  CoverageCode: string | null;
  CreatedDate: Generated<Date | null>;
  DisplayName: string | null;
  HomeCoverageUID: Generated<string>;
  HomeInsuredUID: string;
  Limit: string | null;
}

export interface HomeCoverageDefinition {
  CoverageCode: string | null;
  CoverageDefinitionID: Generated<number>;
  DefaultLimit: string | null;
  DisplayName: string | null;
  PolicyType: string | null;
}

export interface HomeInsured {
  AdditionalInterestAddress1: string | null;
  AdditionalInterestCity: string | null;
  AdditionalInterestName: string | null;
  AdditionalInterestState: string | null;
  AdditionalInterestUnitNumber: string | null;
  AdditionalInterestZipCode: string | null;
  Address1: string | null;
  AddressValidated: Generated<boolean>;
  AgencyInternalTransfer: Generated<boolean>;
  BurglarAlarmSystem: string | null;
  BusinessConductedOnProperty: string | null;
  CarrierOffered: string | null;
  City: string | null;
  ConstructionType: string | null;
  ConstructionYear: number | null;
  CreatedByCSR: string | null;
  CreatedDate: Generated<Date | null>;
  DOB: Date | null;
  DownPmtOffered: number | null;
  ElectricalUpdateType: string | null;
  ElectricalUpdateYear: number | null;
  EmailAddress: string | null;
  ExistingDamageRoof: string | null;
  ExistingDamageWalls: string | null;
  ExistingDamateWindows: string | null;
  FeeOffered: number | null;
  FireAlarmSystem: string | null;
  FireScoring: string | null;
  GatedCommunityDiscount: boolean | null;
  Gender: string | null;
  HasAdditionalInsured: string | null;
  HasAutoPolicyDiscount: Generated<boolean>;
  HasBarsOnWindows: string | null;
  HasDivingBoard: string | null;
  HasExteriorAppliances: string | null;
  HasMortgage: string | null;
  HasMultiPolicyDiscount: Generated<boolean>;
  HasNonOperationalVehicles: string | null;
  HasPetBeenAggressive: string | null;
  HasPets: string | null;
  HasPool: Generated<string | null>;
  HasSlide: string | null;
  HasTrampoline: string | null;
  HomeDeductible: string | null;
  HomeInsuredUID: Generated<string>;
  InsuredFirstName: string | null;
  InsuredLastName: string | null;
  InsuredMiddleName: string | null;
  IsCurrentlyInsured: string | null;
  IsOwnedByLLCOrTrust: string | null;
  IsPhone: Generated<boolean>;
  IsPoolEmpty: string | null;
  IsPoolFenced: string | null;
  IsTrampolineFenced: string | null;
  IsUnderConstruction: string | null;
  LastSavedByCSR: string | null;
  LastSavedDate: Generated<Date | null>;
  Lat: number | null;
  LeadingDigit: Generated<number | null>;
  LeadSource: string | null;
  Lng: number | null;
  LoanNumber: string | null;
  MaritalStatus: string | null;
  MilesFromFireStation: number | null;
  MonthlyOffered: number | null;
  MonthsAtAddress: number | null;
  NameOfWhoHasDeed: string | null;
  OccupancyType: string | null;
  Occupation: string | null;
  Office: string | null;
  PaymentPlan: string | null;
  PhoneNumber: string | null;
  PlumbingUpdateType: string | null;
  PlumbingUpdateYear: number | null;
  PolicyEffectiveDate: Date | null;
  PolicyExpirationDate: Date | null;
  PolicyType: string | null;
  PoolType: string | null;
  PropertyType: string | null;
  ProtectionClass: string | null;
  PurchaseDate: Date | null;
  QuoteCustomerID: number | null;
  QuoteNumber: number | null;
  ReasonNotSold: string | null;
  ReasonNotSoldAddlNotes: string | null;
  ReasonNotSoldDetails: string | null;
  ReasonShopping: string | null;
  RoofType: string | null;
  RoofUpdateType: string | null;
  RoofUpdateYear: number | null;
  RunsBusinessAtHome: string | null;
  SelectedLanguage: string | null;
  SquareFootage: number | null;
  State: string | null;
  Stories: string | null;
  UnitNumber: string | null;
  WasQuoteSoldAnswer: string | null;
  WasReasonNotSoldNoteAdded: Generated<boolean>;
  ZipCode: string | null;
}

export interface HomeNote {
  CreatedBy: string | null;
  CreatedDate: Generated<Date | null>;
  HomeInsuredUID: string;
  HomeNoteUID: Generated<string>;
  NoteText: string | null;
  NoteType: string | null;
}

export interface HomeRateLineItem {
  Carrier: string | null;
  CreatedDate: Generated<Date | null>;
  HomeRateLineItemUID: Generated<string>;
  HomeRateRequestUID: string;
  MainRate: number | null;
  QuoteURL: string | null;
  StringResponse: string | null;
}

export interface HomeRateRequest {
  CreatedDate: Generated<Date | null>;
  HomeInsuredUID: string;
  HomeRateRequestUID: Generated<string>;
  QuotedBy: string | null;
}

export interface InfoLog {
  CreatedDate: Generated<Date | null>;
  CSR: string | null;
  InfoLogUID: Generated<string>;
  Message: string | null;
  UserName: string | null;
}

export interface ISOVehicle {
  BISymbol: string | null;
  Body: string | null;
  Cylinders: string | null;
  EngineSize: string | null;
  EngineType: string | null;
  FullModel: string | null;
  FWD: string | null;
  ISOVehicleID: Generated<number>;
  Make: string | null;
  Model: string | null;
  MPSymbol: string | null;
  NewVIN: string | null;
  PDSymbol: string | null;
  PISymbol: string | null;
  SLSymbol: string | null;
  VIN: string | null;
  Year: number | null;
}

export interface LeadSourceMap {
  ID: Generated<number>;
  IQLeadSource: string | null;
  IsPhone: Generated<boolean>;
  TRLeadSource: string | null;
}

export interface LeadSourceOption {
  ID: Generated<number>;
  IsActive: Generated<boolean>;
  LeadSource: string | null;
}

export interface Office {
  IsActive: Generated<boolean>;
  OfficeCode: string;
}

export interface OfficeLogin {
  CarrierCode: string | null;
  IsActive: Generated<boolean>;
  OfficeCode: string | null;
  Password: string | null;
  Producer: string | null;
  UID: Generated<string>;
  UserName: string | null;
}

export interface PrefillDriver {
  Action: string | null;
  DOB: string | null;
  FirstName: string | null;
  Gender: string | null;
  LastName: string | null;
  MaritalStatus: string | null;
  MemberCode: string | null;
  PrefillDriverID: Generated<number>;
  PrefillPolicyID: number;
}

export interface PrefillPolicy {
  Address1: string | null;
  AddressStatus: string | null;
  City: string | null;
  CreatedDate: Generated<Date | null>;
  CustomerID: number | null;
  DOB: string | null;
  DomesticDrivers: number | null;
  DriversMatched: number | null;
  FirstName: string | null;
  ForeignDrivers: number | null;
  IsApartment: Generated<boolean | null>;
  LastName: string | null;
  LicenseNumber: string | null;
  PolicyDriverCount: number | null;
  PolicyNumber: string | null;
  PolicyVehicleCount: number | null;
  PolID: number | null;
  PrefillDriverCount: number | null;
  PrefillPolicyID: Generated<number>;
  PrefillVehicleCount: number | null;
  RequestID: string | null;
  RequestSent: Generated<boolean | null>;
  ResponseStatus: string | null;
  State: string | null;
  VehiclesMatched: number | null;
  ZipCode: string | null;
}

export interface PrefillVehicle {
  Action: string | null;
  BodyStyle: string | null;
  BrandedTitleIndicator: Generated<boolean | null>;
  Color: string | null;
  Confidence: string | null;
  Description: string | null;
  FuelType: string | null;
  LeaseIndicator: Generated<boolean | null>;
  Make: string | null;
  MarketValue: string | null;
  Mileage: string | null;
  Model: string | null;
  PlateNumber: string | null;
  PrefillPolicyID: number;
  PrefillVehicleID: Generated<number>;
  PurchaseDate: string | null;
  RegisteredOwner: string | null;
  Trim: string | null;
  Type: string | null;
  VIN: string | null;
  Year: string | null;
}

export interface RateResults {
  AutoRateLineItemUID: string;
  AutoRateRequestUID: string | null;
  BridgedDate: Date | null;
  Carrier: string | null;
  CreatedDate: Date | null;
  Expr1: Date | null;
  InsuredFirstName: string | null;
  InsuredLastName: string | null;
  InsuredUID: string;
  MainRate: number | null;
  QuoteNumber: number | null;
  QuoteURL: string | null;
  StringResponse: string | null;
}

export interface ShoppingReason {
  DisplayOrder: number | null;
  DisplayText: string | null;
  QuoteType: string | null;
  ShoppingReasonID: Generated<number>;
  ValueText: string | null;
}

export interface StateAbbreviation {
  Abbreviation: string;
  FullName: string | null;
}

export interface Sysdiagrams {
  definition: Buffer | null;
  diagram_id: Generated<number>;
  name: unknown;
  principal_id: number;
  version: number | null;
}

export interface UserInfo {
  CSR: string | null;
  EmailAddress: string;
  FirstName: string | null;
  LastName: string | null;
  LastSelectedOffice: string | null;
  PhoneNumber: string | null;
  Role: string | null;
  UserPW: string | null;
}

export interface VeriskToken {
  AccessToken: string | null;
  DateCreated: Date | null;
  DateExpired: Date | null;
  Environment: string | null;
  ExpiresIn: number | null;
  ID: Generated<number>;
  RequestOrigin: string | null;
  Scope: string | null;
  TokenType: string | null;
}

export interface VINData {
  LookupVIN: string | null;
  LookupVIN2: string | null;
  LookupVIN3: string | null;
  Make: string | null;
  Model: string | null;
  VIN: string | null;
  Year: number | null;
}

export interface VINTestQuote {
  CarrierCode: string | null;
  ISOVehicleID: number | null;
  QuotedDate: Date | null;
  StringResult: string | null;
  VIN: string | null;
  VINTestQuoteID: Generated<number>;
}

export interface ViolationOption {
  IsActive: Generated<boolean>;
  ViolationDescription: string;
}

export interface WebQuotesAverageTimeToQuote {
  "Average Elapsed Time": string | null;
}

export interface WebQuotesTimeToQuote {
  Age: number | null;
  CompletedDate: string | null;
  CreatedDate: string | null;
  ElapsedTime: string | null;
  InsuredEmailAddress: string | null;
  InsuredFirstName: string | null;
  InsuredLastName: string | null;
  QuoteNumber: number | null;
}

export interface DB {
  AALLRatingApiKeys: AALLRatingApiKeys;
  AutoDriver: AutoDriver;
  AutoInsured: AutoInsured;
  AutoInsuredPriorPolicy: AutoInsuredPriorPolicy;
  AutoNote: AutoNote;
  AutoPrefillDriver: AutoPrefillDriver;
  AutoPrefillVehicle: AutoPrefillVehicle;
  AutoRateLineItem: AutoRateLineItem;
  AutoRateRequest: AutoRateRequest;
  AutoVehicle: AutoVehicle;
  AutoViolation: AutoViolation;
  AutoWebQuote: AutoWebQuote;
  AutoWebQuoteRates: AutoWebQuoteRates;
  CarrierFieldMap: CarrierFieldMap;
  CarrierNameOption: CarrierNameOption;
  CarrierQuestion: CarrierQuestion;
  CarrierQuoteRule: CarrierQuoteRule;
  CarrierRateInfo: CarrierRateInfo;
  CarrierUser: CarrierUser;
  CarrierViolationMap: CarrierViolationMap;
  ErrorLog: ErrorLog;
  HomeAdditionalInsured: HomeAdditionalInsured;
  HomeCoverage: HomeCoverage;
  HomeCoverageDefinition: HomeCoverageDefinition;
  HomeInsured: HomeInsured;
  HomeNote: HomeNote;
  HomeRateLineItem: HomeRateLineItem;
  HomeRateRequest: HomeRateRequest;
  InfoLog: InfoLog;
  ISOVehicle: ISOVehicle;
  LeadSourceMap: LeadSourceMap;
  LeadSourceOption: LeadSourceOption;
  Office: Office;
  OfficeLogin: OfficeLogin;
  PrefillDriver: PrefillDriver;
  PrefillPolicy: PrefillPolicy;
  PrefillVehicle: PrefillVehicle;
  RateResults: RateResults;
  ShoppingReason: ShoppingReason;
  StateAbbreviation: StateAbbreviation;
  sysdiagrams: Sysdiagrams;
  UserInfo: UserInfo;
  VeriskToken: VeriskToken;
  VINData: VINData;
  VINTestQuote: VINTestQuote;
  ViolationOption: ViolationOption;
  WebQuotesAverageTimeToQuote: WebQuotesAverageTimeToQuote;
  WebQuotesTimeToQuote: WebQuotesTimeToQuote;
}
